<?php

/**
 * BaseDecoupage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $libelle
 * @property Doctrine_Collection $Secteurs
 * 
 * @method string              getLibelle()  Returns the current record's "libelle" value
 * @method Doctrine_Collection getSecteurs() Returns the current record's "Secteurs" collection
 * @method Decoupage           setLibelle()  Sets the current record's "libelle" value
 * @method Decoupage           setSecteurs() Sets the current record's "Secteurs" collection
 * 
 * @package    population
 * @subpackage model
 * @author     Flament Guillaume
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDecoupage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('decoupage');
        $this->hasColumn('libelle', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Secteur as Secteurs', array(
             'local' => 'id',
             'foreign' => 'idDecoupage'));
    }
}