<?php

/**
 * BaseRue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $codeRivoli
 * @property string $nom
 * @property string $motDirecteur
 * @property integer $premierNumero
 * @property integer $dernierNumero
 * @property integer $idTypeRue
 * @property TypeRue $TypeRue
 * @property Doctrine_Collection $Adresses
 * @property Doctrine_Collection $Troncons
 * 
 * @method string              getCodeRivoli()    Returns the current record's "codeRivoli" value
 * @method string              getNom()           Returns the current record's "nom" value
 * @method string              getMotDirecteur()  Returns the current record's "motDirecteur" value
 * @method integer             getPremierNumero() Returns the current record's "premierNumero" value
 * @method integer             getDernierNumero() Returns the current record's "dernierNumero" value
 * @method integer             getIdTypeRue()     Returns the current record's "idTypeRue" value
 * @method TypeRue             getTypeRue()       Returns the current record's "TypeRue" value
 * @method Doctrine_Collection getAdresses()      Returns the current record's "Adresses" collection
 * @method Doctrine_Collection getTroncons()      Returns the current record's "Troncons" collection
 * @method Rue                 setCodeRivoli()    Sets the current record's "codeRivoli" value
 * @method Rue                 setNom()           Sets the current record's "nom" value
 * @method Rue                 setMotDirecteur()  Sets the current record's "motDirecteur" value
 * @method Rue                 setPremierNumero() Sets the current record's "premierNumero" value
 * @method Rue                 setDernierNumero() Sets the current record's "dernierNumero" value
 * @method Rue                 setIdTypeRue()     Sets the current record's "idTypeRue" value
 * @method Rue                 setTypeRue()       Sets the current record's "TypeRue" value
 * @method Rue                 setAdresses()      Sets the current record's "Adresses" collection
 * @method Rue                 setTroncons()      Sets the current record's "Troncons" collection
 * 
 * @package    population
 * @subpackage model
 * @author     Flament Guillaume
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rue');
        $this->hasColumn('codeRivoli', 'string', 8, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 8,
             ));
        $this->hasColumn('nom', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('motDirecteur', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('premierNumero', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('dernierNumero', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idTypeRue', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TypeRue', array(
             'local' => 'idTypeRue',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Adresse as Adresses', array(
             'local' => 'id',
             'foreign' => 'idRue'));

        $this->hasMany('Troncon as Troncons', array(
             'local' => 'id',
             'foreign' => 'idRue'));
    }
}