<?php

/**
 * BaseTroncon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idRue
 * @property integer $idSecteur
 * @property integer $numDebutPair
 * @property integer $numDebutImpair
 * @property integer $numFinPair
 * @property integer $numFinImpair
 * @property string $infosComplementaires
 * @property Rue $Rue
 * @property Secteur $Secteur
 * 
 * @method integer getIdRue()                Returns the current record's "idRue" value
 * @method integer getIdSecteur()            Returns the current record's "idSecteur" value
 * @method integer getNumDebutPair()         Returns the current record's "numDebutPair" value
 * @method integer getNumDebutImpair()       Returns the current record's "numDebutImpair" value
 * @method integer getNumFinPair()           Returns the current record's "numFinPair" value
 * @method integer getNumFinImpair()         Returns the current record's "numFinImpair" value
 * @method string  getInfosComplementaires() Returns the current record's "infosComplementaires" value
 * @method Rue     getRue()                  Returns the current record's "Rue" value
 * @method Secteur getSecteur()              Returns the current record's "Secteur" value
 * @method Troncon setIdRue()                Sets the current record's "idRue" value
 * @method Troncon setIdSecteur()            Sets the current record's "idSecteur" value
 * @method Troncon setNumDebutPair()         Sets the current record's "numDebutPair" value
 * @method Troncon setNumDebutImpair()       Sets the current record's "numDebutImpair" value
 * @method Troncon setNumFinPair()           Sets the current record's "numFinPair" value
 * @method Troncon setNumFinImpair()         Sets the current record's "numFinImpair" value
 * @method Troncon setInfosComplementaires() Sets the current record's "infosComplementaires" value
 * @method Troncon setRue()                  Sets the current record's "Rue" value
 * @method Troncon setSecteur()              Sets the current record's "Secteur" value
 * 
 * 
 * @package    population
 * @subpackage model
 * @author     Flament Guillaume
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTroncon extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('troncon');
        $this->hasColumn('idRue', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idSecteur', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('numDebutPair', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('numDebutImpair', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('numFinPair', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('numFinImpair', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('infosComplementaires', 'string', 75, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 75,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Rue', array(
             'local' => 'idRue',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Secteur', array(
             'local' => 'idSecteur',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}