<?php

/**
 * BaseTypeRue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $libelle
 * @property Doctrine_Collection $Rues
 * 
 * @method string              getLibelle() Returns the current record's "libelle" value
 * @method Doctrine_Collection getRues()    Returns the current record's "Rues" collection
 * @method TypeRue             setLibelle() Sets the current record's "libelle" value
 * @method TypeRue             setRues()    Sets the current record's "Rues" collection
 * 
 * @package    population
 * @subpackage model
 * @author     Flament Guillaume
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTypeRue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('type_rue');
        $this->hasColumn('libelle', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Rue as Rues', array(
             'local' => 'id',
             'foreign' => 'idTypeRue'));
    }
}