<?php

/**
 * BaseAdresse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $numeroRue
 * @property string $complement
 * @property integer $nbLogementsMax
 * @property string $infosComplementaires
 * @property integer $idRue
 * @property Rue $Rue
 * @property Doctrine_Collection $Logements
 * 
 * @method integer             getNumeroRue()            Returns the current record's "numeroRue" value
 * @method string              getComplement()           Returns the current record's "complement" value
 * @method integer             getNbLogementsMax()       Returns the current record's "nbLogementsMax" value
 * @method string              getInfosComplementaires() Returns the current record's "infosComplementaires" value
 * @method integer             getIdRue()                Returns the current record's "idRue" value
 * @method Rue                 getRue()                  Returns the current record's "Rue" value
 * @method Doctrine_Collection getLogements()            Returns the current record's "Logements" collection
 * @method Adresse             setNumeroRue()            Sets the current record's "numeroRue" value
 * @method Adresse             setComplement()           Sets the current record's "complement" value
 * @method Adresse             setNbLogementsMax()       Sets the current record's "nbLogementsMax" value
 * @method Adresse             setInfosComplementaires() Sets the current record's "infosComplementaires" value
 * @method Adresse             setIdRue()                Sets the current record's "idRue" value
 * @method Adresse             setRue()                  Sets the current record's "Rue" value
 * @method Adresse             setLogements()            Sets the current record's "Logements" collection
 * 
 * @package    population
 * @subpackage model
 * @author     Flament Guillaume
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdresse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('adresse');
        $this->hasColumn('numeroRue', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('complement', 'string', 10, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 10,
             ));
        $this->hasColumn('nbLogementsMax', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('infosComplementaires', 'string', 75, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 75,
             ));
        $this->hasColumn('idRue', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Rue', array(
             'local' => 'idRue',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Logement as Logements', array(
             'local' => 'id',
             'foreign' => 'idAdresse'));
    }
}