<?php

/**
 * BaseArchive
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nomNaissance
 * @property string $nomUsage
 * @property string $prenoms
 * @property string $titre
 * @property enum $sexe
 * @property date $dateNaissance
 * @property integer $idVilleNaissance
 * @property enum $situationFamiliale
 * @property string $nomRueAnt
 * @property string $typeRueAnt
 * @property integer $numeroRueAnt
 * @property string $complementNumAnt
 * @property string $nomRuePost
 * @property string $typeRuePost
 * @property integer $numeroRuePost
 * @property string $complementNumPost
 * @property date $dateArchivage
 * @property enum $motifDepart
 * @property string $infosComplementaires
 * @property Ville $villeNaissance
 * 
 * @method string  getNomNaissance()         Returns the current record's "nomNaissance" value
 * @method string  getNomUsage()             Returns the current record's "nomUsage" value
 * @method string  getPrenoms()              Returns the current record's "prenoms" value
 * @method string  getTitre()                Returns the current record's "titre" value
 * @method enum    getSexe()                 Returns the current record's "sexe" value
 * @method date    getDateNaissance()        Returns the current record's "dateNaissance" value
 * @method integer getIdVilleNaissance()     Returns the current record's "idVilleNaissance" value
 * @method enum    getSituationFamiliale()   Returns the current record's "situationFamiliale" value
 * @method string  getNomRueAnt()            Returns the current record's "nomRueAnt" value
 * @method string  getTypeRueAnt()           Returns the current record's "typeRueAnt" value
 * @method integer getNumeroRueAnt()         Returns the current record's "numeroRueAnt" value
 * @method string  getComplementNumAnt()     Returns the current record's "complementNumAnt" value
 * @method string  getNomRuePost()           Returns the current record's "nomRuePost" value
 * @method string  getTypeRuePost()          Returns the current record's "typeRuePost" value
 * @method integer getNumeroRuePost()        Returns the current record's "numeroRuePost" value
 * @method string  getComplementNumPost()    Returns the current record's "complementNumPost" value
 * @method date    getDateArchivage()        Returns the current record's "dateArchivage" value
 * @method enum    getMotifDepart()          Returns the current record's "motifDepart" value
 * @method string  getInfosComplementaires() Returns the current record's "infosComplementaires" value
 * @method Ville   getVilleNaissance()       Returns the current record's "villeNaissance" value
 * @method Archive setNomNaissance()         Sets the current record's "nomNaissance" value
 * @method Archive setNomUsage()             Sets the current record's "nomUsage" value
 * @method Archive setPrenoms()              Sets the current record's "prenoms" value
 * @method Archive setTitre()                Sets the current record's "titre" value
 * @method Archive setSexe()                 Sets the current record's "sexe" value
 * @method Archive setDateNaissance()        Sets the current record's "dateNaissance" value
 * @method Archive setIdVilleNaissance()     Sets the current record's "idVilleNaissance" value
 * @method Archive setSituationFamiliale()   Sets the current record's "situationFamiliale" value
 * @method Archive setNomRueAnt()            Sets the current record's "nomRueAnt" value
 * @method Archive setTypeRueAnt()           Sets the current record's "typeRueAnt" value
 * @method Archive setNumeroRueAnt()         Sets the current record's "numeroRueAnt" value
 * @method Archive setComplementNumAnt()     Sets the current record's "complementNumAnt" value
 * @method Archive setNomRuePost()           Sets the current record's "nomRuePost" value
 * @method Archive setTypeRuePost()          Sets the current record's "typeRuePost" value
 * @method Archive setNumeroRuePost()        Sets the current record's "numeroRuePost" value
 * @method Archive setComplementNumPost()    Sets the current record's "complementNumPost" value
 * @method Archive setDateArchivage()        Sets the current record's "dateArchivage" value
 * @method Archive setMotifDepart()          Sets the current record's "motifDepart" value
 * @method Archive setInfosComplementaires() Sets the current record's "infosComplementaires" value
 * @method Archive setVilleNaissance()       Sets the current record's "villeNaissance" value
 * 
 * @package    population
 * @subpackage model
 * @author     Flament Guillaume
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArchive extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('archive');
        $this->hasColumn('nomNaissance', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('nomUsage', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('prenoms', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('titre', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('sexe', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Masculin',
              1 => 'Féminin',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('dateNaissance', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('idVilleNaissance', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('situationFamiliale', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Célibataire',
              1 => 'Marié(e)',
              2 => 'Pacsé(e)',
              3 => 'Veuf(ve)',
              4 => 'Inconnu',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('nomRueAnt', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('typeRueAnt', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('numeroRueAnt', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('complementNumAnt', 'string', 10, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 10,
             ));
        $this->hasColumn('nomRuePost', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
        $this->hasColumn('typeRuePost', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
        $this->hasColumn('numeroRuePost', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('complementNumPost', 'string', 10, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 10,
             ));
        $this->hasColumn('dateArchivage', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('motifDepart', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Mutation',
              1 => 'Départ commune',
              2 => 'Décès',
              3 => 'Inconnu',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('infosComplementaires', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ville as villeNaissance', array(
             'local' => 'idVilleNaissance',
             'foreign' => 'id'));
    }
}