<?php

/**
 * BaseFamille
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idLogement
 * @property string $infosComplementaires
 * @property Logement $Logement
 * @property Doctrine_Collection $Individus
 * 
 * @method integer             getIdLogement()           Returns the current record's "idLogement" value
 * @method string              getInfosComplementaires() Returns the current record's "infosComplementaires" value
 * @method Logement            getLogement()             Returns the current record's "Logement" value
 * @method Doctrine_Collection getIndividus()            Returns the current record's "Individus" collection
 * @method Famille             setIdLogement()           Sets the current record's "idLogement" value
 * @method Famille             setInfosComplementaires() Sets the current record's "infosComplementaires" value
 * @method Famille             setLogement()             Sets the current record's "Logement" value
 * @method Famille             setIndividus()            Sets the current record's "Individus" collection
 * 
 * @package    population
 * @subpackage model
 * @author     Flament Guillaume
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFamille extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('famille');
        $this->hasColumn('idLogement', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('infosComplementaires', 'string', 75, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 75,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Logement', array(
             'local' => 'idLogement',
             'foreign' => 'id'));

        $this->hasMany('Individu as Individus', array(
             'local' => 'id',
             'foreign' => 'idFamille'));
    }
}