<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/12/04 11:49:55

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=127.0.0.1;dbname=population',
  'username' => 'root',
  'password' => 'linux1354prod',
  'name' => 'doctrine',
)),);
