<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/12/04 11:46:35
$this->security = array (
  'login' => 
  array (
    'is_secure' => false,
  ),
  'inscription' => 
  array (
    'is_secure' => false,
  ),
  'logout' => 
  array (
    'is_secure' => true,
  ),
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
