<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/12/04 11:50:00
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'index' => 
  array (
    'is_secure' => false,
  ),
  'show' => 
  array (
    'is_secure' => false,
  ),
  'edit' => 
  array (
    'is_secure' => true,
    'credentials' => 'Admin',
  ),
  'new' => 
  array (
    'is_secure' => true,
    'credentials' => 'Admin',
  ),
  'search' => 
  array (
    'is_secure' => false,
  ),
  'result' => 
  array (
    'is_secure' => false,
  ),
);
