<?php
// auto-generated by sfViewConfigHandler
// date: 2014/12/04 11:46:35
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Application population', false, false);
  $response->addMeta('language', 'fr', false, false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('jquery-ui-1.8.20.custom.css', '', array ());
  $response->addJavascript('slidetoggle.js', '', array ());
  $response->addJavascript('javascript.js', '', array ());
  $response->addJavascript('jquery-1.7.2.min.js', '', array ());
  $response->addJavascript('jquery-ui-1.8.20.custom.min.js', '', array ());
  $response->addJavascript('uidatepicker-fr.js', '', array ());
  $response->addJavascript('chart/chart.js', '', array ());
  $response->addJavascript('chart/highcharts.js', '', array ());


