<?php

/**
 * AdresseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdresseTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object AdresseTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Adresse');
    }
    
    public function getAdressesSortedById() {
        $q = $this->createQuery('a')
                        ->orderBy('a.id ASC');
        return $q;
    }

    public function getAdressesByRue($idRue) {
        $q = $this->createQuery('a')
                        ->where('a.idRue =?', $idRue);
        return $q;
    }

}