<?php

/**
 * Adresse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    population
 * @subpackage model
 * @author     Flament Guillaume
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Adresse extends BaseAdresse
{
    public function __toString() {
        return $this->getNumeroRue() . " " . ($this->getComplement()!=""?$this->getComplement()." ":"") . $this->getRue()->getTypeRue()->getLibelle() . " " . $this->getRue()->getNom();
    }

    // retourne le nombre de logements qu'il est encore possible d'associer à l'adresse
    public function getNbLogementsDispo(){
        return $this->getNbLogementsMax() - $this->getLogements()->count();
    }

    // retourne le nombre de logements non occupés à l'adresse
    public function getNbLogementsVides(){
        $nb = 0;
        foreach ($this->getLogements() as $log) {
            if ($log->getFamilles()->count() == 0) {
                $nb++;
            }
        }
        return $nb;
    }

    // retourne le nombre de logements occupés à l'adresse
    public function getNbLogementsOccupes(){
        $nb = 0;
        foreach ($this->getLogements() as $log) {
            if ($log->getFamilles()->count() != 0) {
                $nb++;
            }
        }
        return $nb;
    }

    /**
     * Fonction qui me permet de vérifier si un numéro de rue est pair
     */
    public function isNumeroRuePair()
    {
        $pair = false;
        
        $reste = $this->getNumeroRue() % 2;

        if($reste == 0)
            $pair = true;

        return $pair;

    }



    /**
     * Fonction scopper au autre classe afin de retourner si le numéro de rue est pair ou impair
     */
    public function pariteNumeroRue()
    {
        $parite = "";

        if($this->isNumeroRuePair())
            $parite = "pair";
        else
            $parite = "impair";

        return $parite;
    }
}
