<?php

/**
 * ArchiveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArchiveTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ArchiveTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Archive');
    }
    
    public function getArchivesByMotif($motif) {
        
        $q = $this->createQuery('a')
                        ->where('a.motifDepart =?', $motif);
        return $q;
    }
    
    public function getArchivesSortedById(){
        $q = $this->createQuery('a')
                ->orderBy('a.id DESC');
        return $q;
    }

}