<?php

/**
 * DecoupageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DecoupageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DecoupageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Decoupage');
    }
}