<?php

/**
 * Decoupage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    population
 * @subpackage model
 * @author     Flament Guillaume
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Decoupage extends BaseDecoupage
{
    public function __tostring(){
        return $this->getLibelle();
    }
    
        
    public function getNbrue()
    {
        
        
        
        // get Doctrine_Connection object
        $con = Doctrine_Manager::getInstance()->connection();
        // execute SQL query, receive Doctrine_Connection_Statement
        $st = $con->execute(" SELECT count( DISTINCT (
                r.id
                ) )
                FROM decoupage d
                JOIN secteur s ON d.id = s.iddecoupage
                JOIN troncon t ON t.idsecteur = s.id
                JOIN rue r ON r.id = t.idrue
                WHERE d.id =".$this->getId());
        
       // fetch query result
        $r = $st->fetch();
       
        return $r[0];
        
        
        
    }
    
    
    
    
    

}
