<?php

/**
 * FamilleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FamilleTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object FamilleTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Famille');
    }

    public function getFamillesSortedById() {
        $q = $this->createQuery('f')
                ->orderBy('f.id ASC');
        return $q;
    }
    
    /* fonction qui prend en paramètres :
     *  - [Optionnel] un champ sur lequel effectuer le tri, sur l'id par défaut
     *  - [Optionnel] un ordre de tri à 'ASC' par défaut
     * et renvoie une requete executable qui retournera une 
     * collection d'enregistrements triés selon les critères
     */
    public function getFamillesSortedBy($tri="id", $ord="ASC"){
        $q = $this->createQuery('f')
                ->orderBy('f.' . $tri . ' ' . $ord);
        return $q;
    }

    public function getFamillesByLogement($log) {
        $q = $this->createQuery('f')
                ->where('f.idLogement =?', $log);
        return $q;
    }

    public function getFamillesByAdresse($adr) {
        $q = $this->createQuery('f')
                ->leftjoin('f.Logement l')
                ->where('l.idAdresse =?', $adr);
        return $q;
    }

}