<?php

/**
 * Individu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    population
 * @subpackage model
 * @author     Flament Guillaume
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Individu extends BaseIndividu
{
    public function getAdresseComplete(){
        if ($this->getFamille()) {
            return $this->getFamille()->getLogement()->getAdresse();
        } else {
            return "";
        }
        
    }

    /**
     * Fonction utilisé lorsque l'on récupère tout les individus sans le traitment par tronçon.
     * Elle permet de vérifier si la rue est bien présent dans les troncon du secteur choisie
     * (troncon hydrater via la recherche, on ne récupère pas tout les tronçon de l'individus)
     *
     * @return <type> 
     */
    public function getIndividuPresentDansSecteur()
    {

      //Initialisation : il est censé être deans le secteur à la base
        $presentDansSecteur = false;

        //On récupère le numéro de la rue
        $numeroRue = $this->getFamille()->getLogement()->getAdresse()->getNumeroRue();


        //On parcours tout les troncons de chacun des secteurs pour cette adresse dans la rue dans laquelle elle se situe (une adresse n'a qu'une rue)
       foreach($this->getFamille()->getLogement()->getAdresse()->getRue()->getTroncons() as $unTroncon)
        {

            //On vérifie si l'adresse est dans l'intervalle (on enlève la sécurité plus présente sous els nouvelle version de Symfony)
            if($unTroncon->getAdresseDisponible(sfOutputEscaper::unescape($this->getFamille()->getLogement()->getAdresse())))
            {
                //Si c'est la cas on garde
                //echo "Ce troncon est dans les clou !<br/>";
                $presentDansSecteur = true;
            }
           /* else
            {
                //Isnon on la vire...mais elle peut repasser à true si dans un autre troncons elle est présente
               // echo "Ce troncon n'est pas dans les clou !<br/>";
               // echo '<pre>';
               // print_r($this->getNomUsage());
                //echo '</pre>';
                $presentDansSecteur = false;
            }*/
        }

        return $presentDansSecteur;
     }

     
}
