<?php

/**
 * IndividuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IndividuTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object IndividuTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Individu');
    }

    public function getIndividusByAdresse($adr) {
        $q = $this->createQuery('i')
                        ->leftjoin('i.Famille f')
                        ->leftjoin('f.Logement l')
                        ->where('l.idAdresse =?', $adr);
        return $q;
    }
    
    public function getIndividusSortedByName(){
        $q = $this->createQuery('i')
                ->orderBy('i.nomNaissance ASC');
        return $q;
    }

    public function getIndividusSortedById(){
        $q = $this->createQuery('i')
                ->orderBy('i.id ASC');
        return $q;
    }

    /* fonction qui prend en paramètres :
     *  - [Optionnel] un champ sur lequel effectuer le tri, sur l'id par défaut
     *  - [Optionnel] un ordre de tri à 'ASC' par défaut
     */
    public function getIndividusSortedBy($tri="id", $ord="ASC"){
        $q = $this->createQuery('i')
                ->orderBy('i.' . $tri . ' ' . $ord);
        return $q;
    }
    
    /*public function getStatsByTrancheAge($sexe, $ageMin=0, $ageMax=150) {
        $date = date('d/m/Y');
        $yearMin = $date['year'] - $ageMax;
        $yearMax = $date['year'] - $ageMin;
        $dateMin = date("d/m/$yearMin");
        $dateMax = date("d/m/$yearMax");
        
        $q = $this->createQuery('i')
                ->select('count(*)')
                ->where('i.sexe=?', $sexe)
                ->andWhere('i.dateNaissance >= ?', $dateMin)
                ->andWhere('i.dateNaissance <= ?', $dateMax);
        
        return $q->execute()->toArray();
    }*/

}