<?php

/**
 * LogementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogementTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object LogementTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Logement');
    }
    
    public function getLogementsSortedById() {
        $q = $this->createQuery('l')
                        ->orderBy('l.id ASC');
        return $q;
    }

    public function getLogementsByAdresse($adr) {
        $q = $this->createQuery('l')
                        ->where('l.idAdresse =?', $adr);
        return $q;
    }

}