<?php

/**
 * Rue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    population
 * @subpackage model
 * @author     Flament Guillaume
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Rue extends BaseRue
{
    public function __toString() {
        return $this->getMotDirecteur() . " (" . $this->getTypeRue() . " " . $this->getNom() . ")";
    }
        
}
