<?php

/**
 * TypeRueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeRueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypeRueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TypeRue');
    }
}