<?php

/**
 * UtilisateurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtilisateurTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object UtilisateurTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Utilisateur');
    }

     /**
     * Retourne vrai si le login et le mot de passent correspondent à un utilisateur
     * dans la base de données
     *
     * @return boolean
     */
    public static function verifierLogin($login, $password){
        $resultat = Doctrine_Core::getTable('Utilisateur')
                        ->createQuery('a')
                        ->where('login= ?', $login)
                        ->andWhere('password= ?', $password)
                        ->execute();

        return $resultat->count()==1;
    }

     /**
     * Retourne l'utilisateur correspondant au login et password
     * dans la base de données
     *
     * @return objet Utilisateur
     */
     public static function login($login, $password){
        $resultat = Doctrine_Core::getTable('Utilisateur')
                        ->createQuery('a')
                        ->where('login= ?', $login)
                        ->andWhere('password= ?', $password)
                        ->execute();

        return $resultat->getFirst();
    }

}