<?php

/**
 * Ville
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    population
 * @subpackage model
 * @author     Flament Guillaume
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Ville extends BaseVille {

    public function __toString() {
        return $this->getVille() . " (" . $this->getDepartement() . ")";
    }

    public static function getVilleCP($a) {
        $r = Doctrine_core::getTable("Ville")->find($a);
        if ($r != null) {
            return ($r->getVille() . " (" . $r->getCP() . ")");
        } else {
            return $a;
        }
    }

    public static function getVilleDepartement($a) {
        $r = Doctrine_core::getTable("Ville")->find($a);
        if ($r != null) {
            return ($r->getVille() . " (" . $r->getDepartement() . ")");
        } else {
            return $a;
        }
    }

}
